import Head from 'next/head'
import dynamic from "next/dynamic";
import {message, Layout} from "antd";
import {useEffect, useState} from "react";
import {useRouter} from "next/router";
import axios from "axios";
import axiosClient from "@/services/axios";
import {IPostsResponse} from "@/utils/post";



const Posts = dynamic(() => import('../components/posts'), {ssr: false})
export default function Home() {
    const [messageApi, contextHolder] = message.useMessage();
    const [posts, setPosts] = useState<Partial<IPostsResponse[]> | null>(null)
    const router = useRouter()

    const [loading, setLoading] = useState(false);


    useEffect(() => {
        search()
        setInterval(() => {
            search()
        }, 10000);

    }, [])


    function search() {
        setLoading(true)
        axiosClient.get('posts').then((response) => {
            setPosts(response.data)
        }).catch(error => {
            messageApi.error({
                content: 'امکان نمایش پست ها وجود ندارد'
            })
        });

    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div style={{width: '100vh', height: '100vh'}}>
                {contextHolder}
                {
                    posts?.map(i => <p>{i?.title}</p>)
                }
                asddasdd
            </div>
        </>
    )
}
