import Head from 'next/head'
import {message, Card, Skeleton, Row, Col} from "antd";
import {Fragment, useEffect, useState} from "react";
import {useRouter} from "next/router";
import axiosClient from "@/services/axios";
import {IPostsResponse} from "@/utils/post";

const {Meta} = Card;

export default function Home() {

    //region <<< useState >>>
    const [messageApi, contextHolder] = message.useMessage();
    const [posts, setPosts] = useState<Partial<IPostsResponse[]> | null>(null)
    const router = useRouter()
    const [loading, setLoading] = useState(true);


    //endregion

    //region <<< useEffect >>>
    useEffect(() => {
        search()
        setInterval(() => {
            search()
        }, 10000);

    }, [])

    //endregion

    //region <<< function >>>
    function search() {
        axiosClient.get('posts').then((response) => {
            if (loading)
                setLoading(false)

            setPosts(response.data)

        }).catch(_ => {
            messageApi.error({
                content: 'امکان نمایش پست ها وجود ندارد'
            })
        });

    }

//endregion

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={'baseContainer'}>
                {contextHolder}
                <Row justify={'center'} align={'middle'} gutter={[16, 0]}
                     style={{width: '100%', height: '100%', maxWidth: '992px'}}>
                    {
                        posts?.map(post => (
                            <Fragment key={post?.id}>
                                <Col>
                                    {/* Note :به دلیل این که گفته بودین روی پست کلیک کرد جابجا شود*/}
                                    <Card onClick={() => {
                                        router.push(`/post/${post?.id}`)
                                    }}
                                          style={{width: 300, marginTop: 16}}
                                          cover={<img alt={post?.title} src={post?.image}/>}
                                          hoverable>
                                        <Meta title={post?.title} description={`${post?.content.slice(0, 150)}...`}/>
                                        <Skeleton loading={loading}/>
                                    </Card>
                                </Col>
                            </Fragment>
                        ))}
                </Row>
            </main>
        </>
    )
}
